### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by tobrun** [tobrun/kotlin-data-compat#14]
For each feature supported in this project now, and for to be developed features, we should be backing these features with tests. This to make sure we don't regress any implementation. A library that we should look into is:
 - https://github.com/tschuchortdev/kotlin-compile-testing

Setting up tests could be based on how kotlinpoet has set things up:
 - https://github.com/square/kotlinpoet/tree/master/kotlinpoet/src/test/java/com/squareup/kotlinpoet

**Comment by alexander-kulikovskii** [comment]
closed with #17
